# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - main

pr: none

pool:
  name: Default
  demands:
    - Agent.Name -equals vmlsha1

resources:
  - repo: self

variables:
  azureSubscription: 'svc-con-awh-01'
  appName: 'duuksarcmediawiki01'
  appResourceGroupName: 'du-uks-awh-arc-mediawiki01'
  runtimeStack: 'PHP|7.4' # Update this value.
  zipDistribution: 'https://releases.wikimedia.org/mediawiki/1.39/mediawiki-1.39.2.zip'

jobs:
- job: Deployment
  steps:
  - script: |
      set -e
      shopt -s dotglob
      ls -lA
      
      mkdir -p dist
      cd dist
      
      echo Downloading package from "$(zipDistribution)"
      curl --connect-timeout 20 --max-time 60 -L -o dist.zip "$(zipDistribution)"
      
      echo "Extracting folder..."
      unzip -q dist.zip
      rm dist.zip
      DIR=$(ls); mv $DIR/* $DIR/[.]* . && rmdir $DIR

    displayName: Get MediaWiki Release

  - task: ArchiveFiles@2
    displayName: "Archive Files"
    inputs:
      rootFolderOrFile: '$(System.DefaultWorkingDirectory)/dist'
      includeRootFolder: false
      archiveType: "zip"
      archiveFile: "$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip"
      replaceExistingArchive: true

  - task: AzureRmWebAppDeployment@4
    inputs:
      ConnectionType: 'AzureRM'
      appType: 'webAppLinux'
      deployToSlotOrASE: true
      SlotName: 'production'
      WebAppName: '$(appName)'
      ResourceGroupName: '$(appResourceGroupName)'
      azureSubscription: '$(azureSubscription)'
      RuntimeStack: '$(runtimeStack)'
      packageForLinux: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
      #AppSettings: '-DATA_ROOT $(DATA_ROOT)'
      ScriptType: 'Inline Script'
      InlineScript: |
        set -e
        export WORKDIR=$(pwd)
        echo "Working directory is ${WORKDIR}"
        
        ls -lA | head
        echo "$(ls -lA | wc -l) files total"
        
        #ls -lA ${DATA_ROOT}
        #touch ${DATA_ROOT}/test

